# Generated by Django 4.0.4 on 2022-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
